config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root 'startup#index'
 # get 'startup/index'
  
  get    '/help',     to: 'startup#help'
  get    '/about',    to: 'startup#about'
  #get    '/upload',   to: 'upload#fileUpload'
  #post   '/uploadFile',   to: 'upload#uploadFile'
  get    '/register', to: 'users#new'
  get    '/signup',   to: 'users#new'
  get    '/login',    to: 'sessions#new'
  post   '/login',    to: 'sessions#create'
  delete '/logout',   to: 'sessions#destroy'
  post '/downloadFile', to: 'users#downloadFile'
  #get  '/downloadFile', to: 'users#downloadFileLink'
  #post '/uploadFile', to: 'users#uploadFile'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: {maximum: 50}

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum: 255},
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: {case_sensitive: false}
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
    
    mount_uploader :game, GameUploader

    # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to login_url
  end
end

app/controllers/startup_controller.rb
class StartupController < ApplicationController
  
  def index
  end
  
  def about
  end

  def help
  end
  
  def upload
  end

  def login
  end
  
  def register
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy
  
  def index
    #restart server for 'paginate' method to work
    @users = User.paginate(page: params[:page])
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the CSU Gaming Projects Site!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  def uploadFile
    
  end
  
 def downloadFile
    #fromUser = params[:download][:userID]
    gameFile = params[:download][:gameName]
    send_file Rails.root.join('public', 'uploads', 'user', 'game', 'consolidated', gameFile)
 end
 
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation, :game)
    end
    
    # Before filters

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    
    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    
    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
    
   
end

app/helpers/application_helper.rb
module ApplicationHelper
   

end

app/helpers/sessions_helper.rb
module SessionsHelper
    # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end
  
  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  
  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/startup_helper.rb
module StartupHelper
end

app/helpers/users_helper.rb
module UsersHelper
 # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | CSU Games Host</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
  <link href="https://github.com/BlackrockDigital/startbootstrap-modern-business/blob/master/css/bootstrap.css" rel="stylesheet">
  <link href="https://github.com/BlackrockDigital/startbootstrap-modern-business/blob/master/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://blackrockdigital.github.io/startbootstrap-modern-business/css/modern-business.css" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
</head>
<body>
 <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Student Games</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <% if logged_in? %>
                       <li><%= link_to "Users", users_path %></li>
                       <li class="dropdown">
                           <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                              Account <b class="caret"></b>
                           </a>
                           <ul class="dropdown-menu">
                              <li><%= link_to "Profile", current_user %></li>
                              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                              <li class="divider"></li>
                              <li>
                                <%= link_to "Log out", logout_path, method: :delete %>
                              </li>
                            </ul>
                       </li>
                       <li>
                            <%= link_to "Up/Download",  users_path %>
                        </li>
                    <% else %>
                       <li><%= link_to "Log in", login_path %></li>
                   <% end %>
                       
                      
                    <!--<li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                <%= link_to "Upload",  users_path %>
                            </li>
                            <li>
                                <%= link_to "Login",   login_path %>
                            </li>
                            <li>
                                <%= link_to "Register", register_path %>
                            </li>
                            
                        </ul>
                    </li>-->
                    
                    <li>
                        <%= link_to "About",    about_path %>
                    </li>
                    <li>
                        <%= link_to "Help",    help_path %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
<%= yield %>
  <script src="https://raw.githubusercontent.com/BlackrockDigital/startbootstrap-modern-business/master/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="https://raw.githubusercontent.com/BlackrockDigital/startbootstrap-modern-business/master/js/bootstrap.min.js"></script>
    <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/startup/about.html.erb
<% provide(:title, "About") %>
<div class="container">
    <div class="jumbotron">
        <div class ="row">
            <h1>About</h1></br>
            <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
             Phasellus tempor pharetra vulputate.
             Integer vehicula nisi vitae facilisis dignissim. 
             Nulla eget mollis diam, consectetur viverra odio. 
             Ut consectetur augue elit, ac vulputate neque pretium non. 
             Aenean iaculis nulla ut egestas dictum. 
             Nunc sed blandit enim, vitae dapibus ante. 
             Vivamus aliquet sed lorem sit amet finibus. 
             Nulla libero lacus, tincidunt vitae porttitor vitae, tristique sit amet enim. 
             Duis pulvinar felis tincidunt scelerisque feugiat. 
             Sed nec tellus nibh. Nullam sed malesuada massa. 
             Pellentesque leo diam, efficitur sit amet blandit eu, lacinia sit amet diam. 
             Nunc imperdiet volutpat risus eget tincidunt.
            </p>
        </div>
    </div>
</div>

app/views/startup/help.html.erb
<% provide(:title, "Help") %>
<div class="container">
    <div class="jumbotron">
        <div class ="row">
            <h1>Help</h1>
            <div><center><bold>Email:</bold> SiteHelpDesk@example.com / <bold>Phone:</bold> 555-555-1234</center></div></br>
            
            <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
             Phasellus tempor pharetra vulputate.
             Integer vehicula nisi vitae facilisis dignissim. 
             Nulla eget mollis diam, consectetur viverra odio. 
             Ut consectetur augue elit, ac vulputate neque pretium non. 
             Aenean iaculis nulla ut egestas dictum. 
             Nunc sed blandit enim, vitae dapibus ante. 
             Vivamus aliquet sed lorem sit amet finibus. 
             Nulla libero lacus, tincidunt vitae porttitor vitae, tristique sit amet enim. 
             Duis pulvinar felis tincidunt scelerisque feugiat. 
             Sed nec tellus nibh. Nullam sed malesuada massa. 
             Pellentesque leo diam, efficitur sit amet blandit eu, lacinia sit amet diam. 
             Nunc imperdiet volutpat risus eget tincidunt.
            </p>
        </div>
    </div>
</div>

app/views/startup/index.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
  <link href="https://github.com/BlackrockDigital/startbootstrap-modern-business/blob/master/css/bootstrap.css" rel="stylesheet">
  <link href="https://github.com/BlackrockDigital/startbootstrap-modern-business/blob/master/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://blackrockdigital.github.io/startbootstrap-modern-business/css/modern-business.css" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
</head>

<h1><center>CSU Gaming Track Projects</center></h1>

 <header id="myCarousel" class="carousel slide">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="item active">
                <div class="fill" style="background-image:url('http://placehold.it/1900x1080&text=Slide One');"></div>
                <div class="carousel-caption">
                    <h2>Caption 1</h2>
                </div>
            </div>
            <div class="item">
                <div class="fill" style="background-image:url('http://placehold.it/1900x1080&text=Slide Two');"></div>
                <div class="carousel-caption">
                    <h2>Caption 2</h2>
                </div>
            </div>
            <div class="item">
                <div class="fill" style="background-image:url('http://placehold.it/1900x1080&text=Slide Three');"></div>
                <div class="carousel-caption">
                    <h2>Caption 3</h2>
                </div>
            </div>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="icon-next"></span>
        </a>
    </header>
    <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    <center>Dr. Obando's Courses</center>
                </h1>
                <h3><center><%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %></center></h3>
            </div>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4><i class="fa fa-fw fa-check"></i> CPSC 4111 - Games I</h4>
                    </div>
                    <div class="panel-body">
                        <p>This is where a description of the class will go</p>
                        <a href="#" class="btn btn-default">Learn More</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4><i class="fa fa-fw fa-gift"></i>CPSC 4112 - Games II</h4>
                    </div>
                    <div class="panel-body">
                        <p>This is where a description of the class will go</p>                        
                        <a href="#" class="btn btn-default">Learn More</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4><i class="fa fa-fw fa-compass"></i> CPSC 3175 - OOD</h4>
                    </div>
                    <div class="panel-body">
                        <p>Under Construction</p>                       
                        <a href="#" class="btn btn-default">Learn More</a>
                    </div>
                </div>
            </div>
       </div>
</html>

app/views/startup/login.html.erb
<% provide(:title, "Login") %>
<h1>Log-In</h1>
<p>
  
</p>

app/views/startup/register.html.erb
<% provide(:title, "Register") %>
<h1>Register</h1>
<p>
  
</p>

app/views/startup/upload.html.erb
<% provide(:title, "Upload") %>
<h1>Upload</h1>
<p>
  
</p>

app/views/upload/fileUpload.html.erb
<h1>Upload a Game</h1>

<span class="game">
    <%= f.file_field :game %>
</span>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>

<div class="container">
  <div class="jumbotron">
    <div class="row">
      
      <h1>Update your profile</h1>
        <%= form_for(@user) do |f| %>
          <%= render 'shared/error_messages' %>
    
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
    
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
    
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
    
          <%= f.label :password_confirmation, "Confirmation" %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
    
          <%= f.submit "Save changes", class: "btn btn-primary" %>
        <% end %>
    
        <div class="gravatar_edit">
          <%= gravatar_for @user %>
          <a href="http://gravatar.com/emails" target="_blank">change</a>
        </div>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1><center>All users</center></h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="container">
  <div class="jumbotron">
    <div class="row">
      <h1>Register</h1>
      <div class="form">
        <!--<div class="col-md-6 col-md-offset-3">-->
          <%= form_for(@user) do |f| %>
            <%= render 'shared/error_messages' %>
            
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
      
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>
      
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>
      
            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
              
            <%= f.submit "Create my account", class: "btn btn-primary" %>
             
          <% end %>
        </div>
      </div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>


<div class="container">
    <div class="jumbotron">
      <div class="row" >
        <% if current_user.name == @user.name && current_user.admin? %>
        <div class="col-md-6 ">
        <h3><center>Upload a Game</center></h3>
        <%= form_for(@user) do |f| %>
          <span class="game">
            <%= f.file_field :game %>
          </span>
          <%= f.submit "Upload Game", class: "btn btn-primary" %>
        <% end %>
      </div>



      <div class="col-md-6 ">
<% end %>
        <h3><center>Download a Game</center></h3>
        <%= form_for(:download, url: downloadFile_path) do |f| %>
          <!--<h4>User ID</h4><%= f.text_field :userID %></br>-->
          <%= f.text_field :gameName, value: 'gameFileName.exe' %></br>
          <%= f.submit "Download Game", class: "btn btn-primary" %>
        <%end%>
      </div>
      
    </div>
  </div>
</div>

<div class="container">
  <div class="jumbotron">
    <div class="row">
      <aside class="col-md-4">
        <section class="user_info">
          <h1>
            <%= gravatar_for @user %>
            <%= @user.name %>
            <!--@user.game-->
          </h1>
        </section>
      </aside>
    </div>
  </div>
</div>